-- MySQL Script generated by MySQL Workbench
-- Fri Jun 18 03:56:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HayDayDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HayDayDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HayDayDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_persian_ci ;
USE `HayDayDB` ;

-- -----------------------------------------------------
-- Table `HayDayDB`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HayDayDB`.`Accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` NVARCHAR(255) NOT NULL,
  `password` NVARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HayDayDB`.`Barns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HayDayDB`.`Barns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `storage` INT NULL DEFAULT 1,
  `max_storage` INT NULL DEFAULT 5,
  `shovels` INT NULL,
  `nails` INT NULL DEFAULT 1,
  `alfalfas` INT NULL,
  `eggs` INT NULL,
  `wools` INT NULL,
  `level` INT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HayDayDB`.`Silos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HayDayDB`.`Silos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `storage` INT NULL DEFAULT 1,
  `max_storage` INT NULL DEFAULT 10,
  `level` INT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HayDayDB`.`AlfalfaFields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HayDayDB`.`AlfalfaFields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `area` INT NULL,
  `planted_area` INT NULL,
  `plants_condition` INT NULL,
  `planting_day` INT NULL,
  `plowing_condition` INT NULL,
  `plowing_day` INT NULL,
  `level` INT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HayDayDB`.`WheatFields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HayDayDB`.`WheatFields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `area` INT NULL DEFAULT 5,
  `planted_area` INT NULL,
  `plants_condition` INT NULL,
  `planting_day` INT NULL,
  `level` INT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HayDayDB`.`Farms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HayDayDB`.`Farms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `age_in_days` INT NULL,
  `Barn_id` INT NOT NULL,
  `Silo_id` INT NOT NULL,
  `AlfalfaField_id` INT NOT NULL,
  `WheatField_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Barn_id`, `Silo_id`, `AlfalfaField_id`, `WheatField_id`),
  INDEX `fk_Farm_Barn_idx` (`Barn_id` ASC) VISIBLE,
  UNIQUE INDEX `Barn_id_UNIQUE` (`Barn_id` ASC) VISIBLE,
  INDEX `fk_Farm_Silo_idx` (`Silo_id` ASC) INVISIBLE,
  UNIQUE INDEX `Silo_id_UNIQUE` (`Silo_id` ASC) VISIBLE,
  INDEX `fk_Farm_AlfalfaField_idx` (`AlfalfaField_id` ASC) VISIBLE,
  UNIQUE INDEX `AlfalfaField_id_UNIQUE` (`AlfalfaField_id` ASC) VISIBLE,
  INDEX `fk_Farm_WheatField_idx` (`WheatField_id` ASC) VISIBLE,
  UNIQUE INDEX `WheatField_id_UNIQUE` (`WheatField_id` ASC) VISIBLE,
  CONSTRAINT `fk_Farm_Barn`
    FOREIGN KEY (`Barn_id`)
    REFERENCES `HayDayDB`.`Barns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Farm_Silo`
    FOREIGN KEY (`Silo_id`)
    REFERENCES `HayDayDB`.`Silos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Farm_AlfalfaField`
    FOREIGN KEY (`AlfalfaField_id`)
    REFERENCES `HayDayDB`.`AlfalfaFields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Farm_WheatField`
    FOREIGN KEY (`WheatField_id`)
    REFERENCES `HayDayDB`.`WheatFields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HayDayDB`.`Farmers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HayDayDB`.`Farmers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` NVARCHAR(255) NOT NULL,
  `coins` INT NULL DEFAULT 20,
  `level` INT NULL DEFAULT 1,
  `xp` INT NULL,
  `max_xp` INT NULL DEFAULT 10,
  `joining_date` TIMESTAMP NULL,
  `Farm_id` INT NOT NULL,
  `Account_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Farm_id`, `Account_id`),
  INDEX `fk_Farmer_Farm_idx` (`Farm_id` ASC) VISIBLE,
  UNIQUE INDEX `Farm_id_UNIQUE` (`Farm_id` ASC) VISIBLE,
  INDEX `fk_Farmer_Account_idx` (`Account_id` ASC) VISIBLE,
  UNIQUE INDEX `Account_id_UNIQUE` (`Account_id` ASC) VISIBLE,
  CONSTRAINT `fk_Farmer_Farm`
    FOREIGN KEY (`Farm_id`)
    REFERENCES `HayDayDB`.`Farms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Farmer_Account`
    FOREIGN KEY (`Account_id`)
    REFERENCES `HayDayDB`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HayDayDB`.`Milks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HayDayDB`.`Milks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacture_day` INT NULL,
  `expiration_day` INT NULL,
  `Barn_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Barn_id`),
  INDEX `fk_Milks_Barn_idx` (`Barn_id` ASC) VISIBLE,
  CONSTRAINT `fk_Milks_Barn`
    FOREIGN KEY (`Barn_id`)
    REFERENCES `HayDayDB`.`Barns` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HayDayDB`.`LivingPlaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HayDayDB`.`LivingPlaces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL,
  `storage` INT NULL,
  `max_storage` INT NULL,
  `animals_condition` INT NULL,
  `feeding_day` INT NULL,
  `level` INT NULL,
  `Farm_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Farm_id`),
  INDEX `fk_LivingPlace_Farm_idx` (`Farm_id` ASC) VISIBLE,
  CONSTRAINT `fk_LivingPlace_Farm`
    FOREIGN KEY (`Farm_id`)
    REFERENCES `HayDayDB`.`Farms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
